"""add official and temp site id fields

Revision ID: 3ea820fa2c65
Revises: 513d328c35a2
Create Date: 2026-07-03 10:21:41.344855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ea820fa2c65'
down_revision: Union[str, Sequence[str], None] = '513d328c35a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('official_site_id', sa.String(length=50), nullable=True))
    op.add_column('site', sa.Column('temp_site_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'temp_site_code')
    op.drop_column('site', 'official_site_id')
    # ### end Alembic commands ###
