"""initial schema

Revision ID: 513d328c35a2
Revises: 
Create Date: 2026-07-03 09:03:15.010572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '513d328c35a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('region_id', sa.Uuid(), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('admin','project_manager','dt_coordinator','field_subcontractor','regional_manager','viewer')", name='chk_user_role_vocab'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('letter',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('letter_number', sa.String(length=100), nullable=False),
    sa.Column('letter_date', sa.Date(), nullable=False),
    sa.Column('organization', sa.String(length=100), nullable=False),
    sa.Column('province_or_region_id', sa.Uuid(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('pdf_attachment_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('letter_number')
    )
    op.create_table('site',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('province_id', sa.Uuid(), nullable=False),
    sa.Column('region_id', sa.Uuid(), nullable=False),
    sa.Column('on_air_date', sa.Date(), nullable=True),
    sa.Column('assignment_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id')
    )
    op.create_table('impediment_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('reported_by', sa.Uuid(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('length(comment) >= 15', name='chk_comment_length_limit'),
    sa.ForeignKeyConstraint(['reported_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_change',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('village',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('village_id', sa.String(length=50), nullable=False),
    sa.Column('village_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'village_id', name='uq_site_village_composite')
    )
    op.create_table('village_acceptance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('village_id', sa.String(length=50), nullable=False),
    sa.Column('technology', sa.String(length=20), nullable=False),
    sa.Column('ict_status', sa.String(length=20), nullable=False),
    sa.Column('cra_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'village_id', 'technology', name='uq_acceptance_composite_key')
    )
    op.create_table('work_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('site_type', sa.String(length=100), nullable=False),
    sa.Column('assignment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'site_type', name='uq_site_type_composite')
    )
    op.create_table('contractor_assignment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('work_item_id', sa.Uuid(), nullable=False),
    sa.Column('contractor_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= assigned_at', name='chk_assignment_timeline_logic'),
    sa.ForeignKeyConstraint(['assigned_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['contractor_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_item.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drive_test',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('work_item_id', sa.Uuid(), nullable=False),
    sa.Column('contractor_id', sa.Uuid(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('report_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_item.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_check',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('work_item_id', sa.Uuid(), nullable=False),
    sa.Column('contractor_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_item.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('letter_village_mapping',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('letter_id', sa.Uuid(), nullable=False),
    sa.Column('village_acceptance_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['letter_id'], ['letter.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['village_acceptance_id'], ['village_acceptance.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('letter_id', 'village_acceptance_id', name='uq_letter_target_mapping')
    )
    op.create_table('timeline_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('work_item_id', sa.Uuid(), nullable=True),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_item_technology',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('work_item_id', sa.Uuid(), nullable=False),
    sa.Column('technology', sa.String(length=20), nullable=False),
    sa.Column('on_air_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drive_test_review',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('drive_test_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer', sa.Uuid(), nullable=False),
    sa.Column('review_level', sa.String(length=50), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('review_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['drive_test_id'], ['drive_test.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewer'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drive_test_review')
    op.drop_table('work_item_technology')
    op.drop_table('timeline_event')
    op.drop_table('letter_village_mapping')
    op.drop_table('health_check')
    op.drop_table('drive_test')
    op.drop_table('contractor_assignment')
    op.drop_table('work_item')
    op.drop_table('village_acceptance')
    op.drop_table('village')
    op.drop_table('pending_change')
    op.drop_table('impediment_log')
    op.drop_table('site')
    op.drop_table('letter')
    op.drop_table('app_user')
    # ### end Alembic commands ###
