"""add work item and village on-air tracking

Revision ID: 593666be591d
Revises: 3ea820fa2c65
Create Date: 2026-07-03 10:38:41.295519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '593666be591d'
down_revision: Union[str, Sequence[str], None] = '3ea820fa2c65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('village', sa.Column('is_on_air', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('work_item', sa.Column('cpm_raw_status', sa.String(length=100), nullable=True))
    op.add_column('work_item', sa.Column('is_on_air', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    with op.batch_alter_table('work_item') as batch_op:
        batch_op.alter_column('assignment_date', existing_type=sa.DATE(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_item', 'assignment_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('work_item', 'is_on_air')
    op.drop_column('work_item', 'cpm_raw_status')
    op.drop_column('village', 'is_on_air')
    # ### end Alembic commands ###
