"""add user region name, keep region id for future use

Revision ID: d383bcacc911
Revises: d85874b4e537
Create Date: 2026-07-03 11:09:50.023502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd383bcacc911'
down_revision: Union[str, Sequence[str], None] = 'd85874b4e537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('region_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'region_name')
    # ### end Alembic commands ###
