"""add province and region name fields

Revision ID: d85874b4e537
Revises: 593666be591d
Create Date: 2026-07-03 10:56:16.809170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd85874b4e537'
down_revision: Union[str, Sequence[str], None] = '593666be591d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('province_name', sa.String(length=100), nullable=True))
    op.add_column('site', sa.Column('region_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'region_name')
    op.drop_column('site', 'province_name')
    # ### end Alembic commands ###
